site_name: Lance

theme:
    name: material
    language: 'pt'
    palette:
        primary: 'green'
        accent: 'yellow'
    logo: 'favicon.png'

repo_name: 'Lance'
repo_url: 'https://github.com/Interacao-Humano-Computador/2019.2-Lance'

plugins:
    - search

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
