site_name: Lance

theme:
    name: material
    language: 'pt'
    palette:
        primary: 'green'
        accent: 'yellow'
    logo: 'favicon.png'

repo_name: 'Lance'
repo_url: 'https://github.com/Interacao-Humano-Computador/2019.2-Lance'

plugins:
    - search
    - awesome-pages

